Fixing DMAR parser break caused by classes name change (#117)
This change fixes "AttributeError: 'DMARTable' object has no attribute '**'" due to class name change inside DMAR table class.

The issue was introduced during the porting process from Project Mu.